# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteDbDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogDelete_Db(object):
    def setupUi(self, DialogDelete_Db):
        DialogDelete_Db.setObjectName("DialogDelete_Db")
        DialogDelete_Db.resize(240, 101)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogDelete_Db)
        self.buttonBox.setGeometry(QtCore.QRect(10, 50, 221, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.ComboBox_For_DbModels = QtWidgets.QComboBox(DialogDelete_Db)
        self.ComboBox_For_DbModels.setGeometry(QtCore.QRect(10, 30, 69, 22))
        self.ComboBox_For_DbModels.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border: none;\n"
"border-bottom: 2px solid #E0E0E0;\n"
"")
        self.ComboBox_For_DbModels.setObjectName("ComboBox_For_DbModels")
        self.ComboBox_For_DbModels.addItem("")
        self.ComboBox_For_DbModels.addItem("")
        self.ComboBox_For_DbModels.addItem("")
        self.ComboBox_For_DbModels.addItem("")
        self.lineEdit_for_delete = QtWidgets.QLineEdit(DialogDelete_Db)
        self.lineEdit_for_delete.setGeometry(QtCore.QRect(90, 30, 113, 20))
        self.lineEdit_for_delete.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border: none;\n"
"border-bottom: 2px solid #E0E0E0;\n"
"")
        self.lineEdit_for_delete.setObjectName("lineEdit_for_delete")
        self.label_delete = QtWidgets.QLabel(DialogDelete_Db)
        self.label_delete.setGeometry(QtCore.QRect(90, 10, 51, 16))
        self.label_delete.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delete.setObjectName("label_delete")

        self.retranslateUi(DialogDelete_Db)
        self.buttonBox.accepted.connect(DialogDelete_Db.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogDelete_Db.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogDelete_Db)

    def retranslateUi(self, DialogDelete_Db):
        _translate = QtCore.QCoreApplication.translate
        DialogDelete_Db.setWindowTitle(_translate("DialogDelete_Db", "Dialog"))
        self.ComboBox_For_DbModels.setItemText(0, _translate("DialogDelete_Db", "КоэфУсв"))
        self.ComboBox_For_DbModels.setItemText(1, _translate("DialogDelete_Db", "ХимСостав"))
        self.ComboBox_For_DbModels.setItemText(2, _translate("DialogDelete_Db", "Проволока"))
        self.ComboBox_For_DbModels.setItemText(3, _translate("DialogDelete_Db", "Марка"))
        self.label_delete.setText(_translate("DialogDelete_Db", "Название"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogDelete_Db = QtWidgets.QDialog()
    ui = Ui_DialogDelete_Db()
    ui.setupUi(DialogDelete_Db)
    DialogDelete_Db.show()
    sys.exit(app.exec_())
