# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateDbDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogUpdate_db(object):
    def setupUi(self, DialogUpdate_db):
        DialogUpdate_db.setObjectName("DialogUpdate_db")
        DialogUpdate_db.resize(257, 148)
        self.buttonBoxOK_Cance = QtWidgets.QDialogButtonBox(DialogUpdate_db)
        self.buttonBoxOK_Cance.setGeometry(QtCore.QRect(30, 110, 221, 41))
        self.buttonBoxOK_Cance.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxOK_Cance.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxOK_Cance.setObjectName("buttonBoxOK_Cance")
        self.scrollArea_For_db = QtWidgets.QScrollArea(DialogUpdate_db)
        self.scrollArea_For_db.setGeometry(QtCore.QRect(90, 20, 161, 80))
        self.scrollArea_For_db.setWidgetResizable(True)
        self.scrollArea_For_db.setObjectName("scrollArea_For_db")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 159, 78))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_For_db.setWidget(self.scrollAreaWidgetContents)
        self.ComboBox_For_DbModels = QtWidgets.QComboBox(DialogUpdate_db)
        self.ComboBox_For_DbModels.setGeometry(QtCore.QRect(10, 20, 69, 22))
        self.ComboBox_For_DbModels.setObjectName("ComboBox_For_DbModels")
        self.ComboBox_For_DbModels.addItem("")
        self.ComboBox_For_DbModels.addItem("")
        self.ComboBox_For_DbModels.addItem("")
        self.ComboBox_For_DbModels.addItem("")
        self.ComboBox_For_DbModels.addItem("")

        self.retranslateUi(DialogUpdate_db)
        self.buttonBoxOK_Cance.accepted.connect(DialogUpdate_db.accept) # type: ignore
        self.buttonBoxOK_Cance.rejected.connect(DialogUpdate_db.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogUpdate_db)

    def retranslateUi(self, DialogUpdate_db):
        _translate = QtCore.QCoreApplication.translate
        DialogUpdate_db.setWindowTitle(_translate("DialogUpdate_db", "Dialog"))
        self.ComboBox_For_DbModels.setItemText(0, _translate("DialogUpdate_db", "Absr"))
        self.ComboBox_For_DbModels.setItemText(1, _translate("DialogUpdate_db", "Ch"))
        self.ComboBox_For_DbModels.setItemText(2, _translate("DialogUpdate_db", "Cr"))
        self.ComboBox_For_DbModels.setItemText(3, _translate("DialogUpdate_db", "Fuse"))
        self.ComboBox_For_DbModels.setItemText(4, _translate("DialogUpdate_db", "Fuse_T"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogUpdate_db = QtWidgets.QDialog()
    ui = Ui_DialogUpdate_db()
    ui.setupUi(DialogUpdate_db)
    DialogUpdate_db.show()
    sys.exit(app.exec_())
