# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculate(object):
    def setupUi(self, Calculate):
        Calculate.setObjectName("Calculate")
        Calculate.resize(426, 485)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Calculate.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Calculate)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_For_main_window = QtWidgets.QWidget(self.centralwidget)
        self.widget_For_main_window.setGeometry(QtCore.QRect(10, 10, 411, 481))
        self.widget_For_main_window.setObjectName("widget_For_main_window")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_For_main_window)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_for_radio_button = QtWidgets.QHBoxLayout()
        self.layout_for_radio_button.setObjectName("layout_for_radio_button")
        self.Main_button_for_RadButton = QtWidgets.QPushButton(self.widget_For_main_window)
        self.Main_button_for_RadButton.setStyleSheet("border:None;")
        self.Main_button_for_RadButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/vector-1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Main_button_for_RadButton.setIcon(icon1)
        self.Main_button_for_RadButton.setObjectName("Main_button_for_RadButton")
        self.layout_for_radio_button.addWidget(self.Main_button_for_RadButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_for_radio_button.addItem(spacerItem)
        self.History_Button = QtWidgets.QPushButton(self.widget_For_main_window)
        self.History_Button.setStyleSheet("border:None;")
        self.History_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/gear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.History_Button.setIcon(icon2)
        self.History_Button.setObjectName("History_Button")
        self.layout_for_radio_button.addWidget(self.History_Button)
        self.verticalLayout.addLayout(self.layout_for_radio_button)
        self.layout_for_main_window = QtWidgets.QHBoxLayout()
        self.layout_for_main_window.setObjectName("layout_for_main_window")
        self.verticalLayout.addLayout(self.layout_for_main_window)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.WIdget_for_radio_Button = QtWidgets.QWidget(self.centralwidget)
        self.WIdget_for_radio_Button.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.WIdget_for_radio_Button.setObjectName("WIdget_for_radio_Button")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.WIdget_for_radio_Button)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_Rad_button = QtWidgets.QHBoxLayout()
        self.main_Rad_button.setObjectName("main_Rad_button")
        self.Lrf1_RadButton = QtWidgets.QRadioButton(self.WIdget_for_radio_Button)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lrf1_RadButton.setFont(font)
        self.Lrf1_RadButton.setStyleSheet("QRadioButton::indicator {\n"
"    width: 0px; \n"
"    height: 0px;\n"
"}")
        self.Lrf1_RadButton.setText("")
        self.Lrf1_RadButton.setObjectName("Lrf1_RadButton")
        self.main_Rad_button.addWidget(self.Lrf1_RadButton)
        self.Lrf2_RadButton = QtWidgets.QRadioButton(self.WIdget_for_radio_Button)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lrf2_RadButton.setFont(font)
        self.Lrf2_RadButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lrf2_RadButton.setAutoFillBackground(False)
        self.Lrf2_RadButton.setStyleSheet("QRadioButton::indicator {\n"
"    width: 0px; /* Убираем стандартный кружок */\n"
"    height: 0px;\n"
"}")
        self.Lrf2_RadButton.setText("")
        self.Lrf2_RadButton.setObjectName("Lrf2_RadButton")
        self.main_Rad_button.addWidget(self.Lrf2_RadButton)
        self.Buck_RadButton = QtWidgets.QRadioButton(self.WIdget_for_radio_Button)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Buck_RadButton.setFont(font)
        self.Buck_RadButton.setStyleSheet("QRadioButton::indicator {\n"
"    width: 0px; /* Убираем стандартный кружок */\n"
"    height: 0px;\n"
"}")
        self.Buck_RadButton.setText("")
        self.Buck_RadButton.setObjectName("Buck_RadButton")
        self.main_Rad_button.addWidget(self.Buck_RadButton)
        self.Form_RadButton = QtWidgets.QRadioButton(self.WIdget_for_radio_Button)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Form_RadButton.setFont(font)
        self.Form_RadButton.setStyleSheet("QRadioButton::indicator {\n"
"    width: 0px; /* Убираем стандартный кружок */\n"
"    height: 0px;\n"
"}")
        self.Form_RadButton.setText("")
        self.Form_RadButton.setObjectName("Form_RadButton")
        self.main_Rad_button.addWidget(self.Form_RadButton)
        self.Note_RadButton = QtWidgets.QRadioButton(self.WIdget_for_radio_Button)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Note_RadButton.setFont(font)
        self.Note_RadButton.setStyleSheet("QRadioButton::indicator {\n"
"    width: 0px; /* Убираем стандартный кружок */\n"
"    height: 0px;\n"
"}")
        self.Note_RadButton.setText("")
        self.Note_RadButton.setObjectName("Note_RadButton")
        self.main_Rad_button.addWidget(self.Note_RadButton)
        self.gridLayout_2.addLayout(self.main_Rad_button, 0, 0, 1, 1)
        self.Widget_For_Db = QtWidgets.QWidget(self.centralwidget)
        self.Widget_For_Db.setGeometry(QtCore.QRect(800, 210, 16, 16))
        self.Widget_For_Db.setObjectName("Widget_For_Db")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Widget_For_Db)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.layout_for_button_in_db = QtWidgets.QHBoxLayout()
        self.layout_for_button_in_db.setObjectName("layout_for_button_in_db")
        self.Button_For_add_in_Db = QtWidgets.QPushButton(self.Widget_For_Db)
        self.Button_For_add_in_Db.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/Frame 116.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_For_add_in_Db.setIcon(icon3)
        self.Button_For_add_in_Db.setObjectName("Button_For_add_in_Db")
        self.layout_for_button_in_db.addWidget(self.Button_For_add_in_Db)
        self.Button_For_update_in_Db = QtWidgets.QPushButton(self.Widget_For_Db)
        self.Button_For_update_in_Db.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/modify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_For_update_in_Db.setIcon(icon4)
        self.Button_For_update_in_Db.setObjectName("Button_For_update_in_Db")
        self.layout_for_button_in_db.addWidget(self.Button_For_update_in_Db)
        self.Button_For_del_in_Db = QtWidgets.QPushButton(self.Widget_For_Db)
        self.Button_For_del_in_Db.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/vector.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_For_del_in_Db.setIcon(icon5)
        self.Button_For_del_in_Db.setObjectName("Button_For_del_in_Db")
        self.layout_for_button_in_db.addWidget(self.Button_For_del_in_Db)
        self.gridLayout_3.addLayout(self.layout_for_button_in_db, 0, 0, 1, 1)
        Calculate.setCentralWidget(self.centralwidget)

        self.retranslateUi(Calculate)
        QtCore.QMetaObject.connectSlotsByName(Calculate)

    def retranslateUi(self, Calculate):
        _translate = QtCore.QCoreApplication.translate
        Calculate.setWindowTitle(_translate("Calculate", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculate = QtWidgets.QMainWindow()
    ui = Ui_Calculate()
    ui.setupUi(Calculate)
    Calculate.show()
    sys.exit(app.exec_())
